 main: iie.HelloWorldPlugin
 version: 1.0.0
 name: HelloWorldPlugin
 commands:
   HelloWorld:
     description: Command that says Hello World!
   debugRTP:
     description: Command that randomly teleports someone inside the hardcore world